### ISSUE TITLE
Vignette typo -  aall should be all

### ISSUE THREAD

**Issue by pssguy** [Ironholds/WikidataR#10]
```
first_aaron <- get_item(aall_aarons[[1]]$id)
```

**Comment by Ironholds** [comment]
Nice catch! Wanna PR it? I'll get to it if not.

**Comment by pssguy** [comment]
I've only ever done one PR before and that was about a year ago. I chnged all 4 files in my fork but pretty sure I did the PR incorrectly!

**Comment by Ironholds** [comment]
Yeah; fork, make all the changes, commit them to the fork, then make a pull request from the fork to this version.

**Comment by Ironholds** [comment]
Okay, I'm going to fix this at my end with one commit.
