### ISSUE TITLE
find_item() Is it possible to use regular expressions

### ISSUE THREAD

**Issue by pssguy** [Ironholds/WikidataR#13]
If I wanted surnames i.e. Kennedy find_item(*Kennedy)

Currently this results in 0

but find_item("Kennedy, limit=1000) just provides first 50 starting Kennedy 
e.g Kennedy-Syndrom, Kennedy Space Center,  Kennedy Leigh

**Comment by Ironholds** [comment]
I don't know if the search system supports regexes but will find out (strictly speaking my day job is to help build it so I should probably find this out _anyway_ :P)

**Comment by Ironholds** [comment]
The answer turns out to be pretty close to no, but I'll try to narrow it down on Monday.

**Comment by Ironholds** [comment]
Update: pinged the upstream person again!

**Comment by Ironholds** [comment]
Answer: the only way is to search the text, not the titles :(.
