### ISSUE TITLE
find_item("Aaron Halfaker") failed

### ISSUE THREAD

**Issue by josefslerka** [Ironholds/WikidataR#26]
Hi, i try to run tutorial examples, but after 

`find_item("Aaron Halfaker")`

I received 

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't resolve host name
```

**Comment by Ironholds** [comment]
Thaaat's weird. Thanks; I'll dig into it.

**Comment by Ironholds** [comment]
@josefslerka this works perfectly for me; how is it for you now? I wonder if it could have been caused by some operations changes Wikimedia was making on Wednesday.

**Comment by josefslerka** [comment]
So strange.

library(WikidataR)
aarons <- find_item("Aaron Halfaker")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't resolve host name

**Comment by Ironholds** [comment]
Huh. Are you behind tor or some kind of proxy?

**Comment by Ironholds** [comment]
And, what version of WikipediR and WikidataR are you using?

**Comment by Ironholds** [comment]
Ping?

**Comment by josefslerka** [comment]
Sorry. 

WikipediR version 1.4.0
WikidataR version 1.3.0

**Comment by josefslerka** [comment]
That was the problem. With new version WikipediR is everything ok. Thnx.

**Comment by Ironholds** [comment]
Yay!
